// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificOperationsCenter.Api.DAL;

#nullable disable

namespace ScientificOperationsCenter.Api.Migrations
{
    [DbContext(typeof(ScientificOperationsCenterContext))]
    partial class ScientificOperationsCenterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientificOperationsCenter.Api.Models.RadiationMeasurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Milligrays")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("RadiationMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 9, 8),
                            Milligrays = 100,
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 9, 8),
                            Milligrays = 140,
                            Time = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 9, 8),
                            Milligrays = 162,
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 8),
                            Milligrays = 100,
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 8),
                            Milligrays = 120,
                            Time = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 10, 8),
                            Milligrays = 190,
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 10, 9),
                            Milligrays = 120,
                            Time = new TimeOnly(21, 30, 0)
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 10, 9),
                            Milligrays = 110,
                            Time = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 10, 9),
                            Milligrays = 160,
                            Time = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 11, 2),
                            Milligrays = 100,
                            Time = new TimeOnly(9, 10, 0)
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 11, 3),
                            Milligrays = 200,
                            Time = new TimeOnly(2, 30, 0)
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 12, 1),
                            Milligrays = 120,
                            Time = new TimeOnly(4, 20, 0)
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 12, 2),
                            Milligrays = 132,
                            Time = new TimeOnly(4, 10, 0)
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 12, 5),
                            Milligrays = 126,
                            Time = new TimeOnly(7, 30, 0)
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2025, 1, 3),
                            Milligrays = 200,
                            Time = new TimeOnly(4, 30, 0)
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2025, 1, 5),
                            Milligrays = 200,
                            Time = new TimeOnly(4, 30, 0)
                        });
                });

            modelBuilder.Entity("ScientificOperationsCenter.Api.Models.Temperatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TemperatureCelcius")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Temperatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 9, 2),
                            TemperatureCelcius = 20,
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 9, 5),
                            TemperatureCelcius = 15,
                            Time = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 9, 7),
                            TemperatureCelcius = -10,
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 8),
                            TemperatureCelcius = -4,
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 8),
                            TemperatureCelcius = 12,
                            Time = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 10, 8),
                            TemperatureCelcius = 11,
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 10, 9),
                            TemperatureCelcius = 12,
                            Time = new TimeOnly(21, 30, 0)
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 10, 9),
                            TemperatureCelcius = 10,
                            Time = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 10, 9),
                            TemperatureCelcius = 9,
                            Time = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 11, 2),
                            TemperatureCelcius = -2,
                            Time = new TimeOnly(9, 10, 0)
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 11, 3),
                            TemperatureCelcius = 5,
                            Time = new TimeOnly(4, 30, 0)
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 12, 21),
                            TemperatureCelcius = 8,
                            Time = new TimeOnly(4, 50, 0)
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 12, 10),
                            TemperatureCelcius = 1,
                            Time = new TimeOnly(4, 10, 0)
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 12, 8),
                            TemperatureCelcius = 5,
                            Time = new TimeOnly(4, 30, 0)
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2025, 1, 3),
                            TemperatureCelcius = 15,
                            Time = new TimeOnly(5, 30, 0)
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2025, 1, 5),
                            TemperatureCelcius = 5,
                            Time = new TimeOnly(3, 30, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
