version: '3.4'
services:
  scientificoperationscenter.client:
    image: ${DOCKER_REGISTRY-}scientificoperationscenterclient
    container_name: scientificoperationscenterclient
    hostname: localhost
    ports:
        - 9000:9000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9000
    build:
      context: .
      dockerfile: ScientificOperationsCenter.Client/Dockerfile
    depends_on:
        - scientificoperationscenter.api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  

  scientificoperationscenter.api:
    image: ${DOCKER_REGISTRY-}scientificoperationscenterapi
    container_name: scientificoperationscenterapi
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    networks:
        - science-net
    build:
      context: .
      dockerfile: ScientificOperationsCenter.Api/Dockerfile
    depends_on:
        - scientificoperationscenter.auth
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
   
  scientificoperationscenter.auth:
    image: ${DOCKER_REGISTRY-}scientificoperationscenterauth
    container_name: scientificoperationscenterauth
    ports:
      - "8060:8060"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8060
    networks:
        - science-net
    build:
      context: .
      dockerfile: ScientificOperationsCenter.Auth/Dockerfile
    depends_on:
        - sqlpreview
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8060/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  sqlpreview:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlpreview
    networks:
        - science-net
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: SATestPassword10*

networks:
    science-net:
        driver: bridge