server {
    listen       9000;
    listen  [::]:9000;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Security headers
    add_header Content-Security-Policy "default-src 'none'; script-src-elem 'self'; style-src-elem 'self'; img-src 'self'; connect-src *;";
    add_header Content-Language "en-CA";
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), bluetooth=(), payment=(), idle-detection=(), accelerometer=(),";

    # Routes that should serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /login {
        try_files $uri $uri/ /index.html;
    }

    location = /temperatures {
        try_files $uri $uri/ /index.html;
    }

    location /temperatures/day {
        try_files $uri $uri/ /index.html;
    }

    location /temperatures/month {
        try_files $uri $uri/ /index.html;
    }

    location /temperatures/year {
        try_files $uri $uri/ /index.html;
    }

    location = /radiation-measurements {
        try_files $uri $uri/ /index.html;
    }

    location /radiation-measurements/day {
        try_files $uri $uri/ /index.html;
    }

    location /radiation-measurements/month {
        try_files $uri $uri/ /index.html;
    }

    location /radiation-measurements/year {
        try_files $uri $uri/ /index.html;
    }
}
