server {
    listen 80;
    server_name localhost;

    # Serve the index.html for the root path and other defined paths
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html for SPA
    }

    location /login {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/day {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/month {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/year {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/day {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/month {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/year {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    # Add other locations as needed
}
