server {
    listen 80;
    server_name localhost;

    # Security headers
    add_header Content-Security-Policy "default-src 'none'; script-src-elem 'self'; style-src-elem 'self'; img-src 'self'; connect-src *;";
    add_header Content-Language "en-CA";
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), bluetooth=(), payment=(), idle-detection=(), accelerometer=();";
    
    # Root directory for static files
    root /usr/share/nginx/html;
    index index.html;
    
    # Serve the index.html for the root path and other defined paths
    location / {
        try_files $uri $uri/ /index.html;  # Fallback to index.html for SPA
    }

    location /login {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/day {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/month {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /temperatures/year {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/day {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/month {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    location /radiation-measurements/year {
        try_files $uri $uri/ /index.html;  # Fallback to index.html
    }

    # Health check endpoint
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Add other locations as needed
}
