name: ScientificOperationsCenter
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
              
          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 8.0.x
          
          - name: Install Tools
            shell: bash
            run: |
              sudo apt install -y nikto doxygen libxml2-utils

          - name: Build and Run App Containers
            shell: bash
            run: docker compose up -d

          - name: Run API Tests
            shell: bash
            run: |
              mkdir -p APITestResults
              dotnet test ./ScientificOperationsCenter.Api.Tests/ScientificOperationsCenter.Api.Tests.csproj \
                --collect:"XPlat Code Coverage" \
                --results-directory ./APITestResults \
                --os linux \
                --verbosity minimal
              
              coverage_file=$(find ./APITestResults -name "coverage.cobertura.xml" -print -quit)
              
              if [ -f "$coverage_file" ]; then
                coverage_percent=$(xmllint --xpath "string(//coverage/@line-rate)" "$coverage_file")
                coverage_percentage=$(echo "$coverage_percent * 100" | bc)
                printf "API Code Coverage: %.1f%%\n" "$coverage_percentage"
              else
                echo "Coverage file not found."
              fi

          - name: Nikto Scan Backend
            shell: bash
            run: |
              nikto -h http://localhost:8000 -C all

          - name: Stop and Remove API Container
            shell: bash
            run: |
              docker rm -f scientificoperationscenterapi

          - name: Stop and Remove Auth Service Container
            shell: bash
            run: |
              docker rm -f scientificoperationscenterauth
              
          - name: Stop and Remove Database Container
            shell: bash
            run: |
              docker rm -f sqlpreview
              
          - name: Run Client Tests
            shell: bash
            run: |
              mkdir -p ClientTestResults
              dotnet test ./ScientificOperationsCenter.Client.Tests/ScientificOperationsCenter.Client.Tests.csproj --collect:"XPlat Code Coverage" --results-directory ./ClientTestResults --os linux --verbosity minimal
              
              coverage_file=$(find ./ClientTestResults -name "coverage.cobertura.xml" -print -quit)
              
              if [ -f "$coverage_file" ]; then
                coverage_percent=$(xmllint --xpath "string(//coverage/@line-rate)" "$coverage_file")
                coverage_percentage=$(echo "$coverage_percent * 100" | bc)
                printf "Client Code Coverage: %.1f%%\n" "$coverage_percentage"
              else
                echo "Coverage file not found."
              fi

          - name: Nikto Scan Frontend
            shell: bash
            run: |
              nikto -h http://localhost:9000 -C all

          - name: Stop and Remove Client Container
            shell: bash
            run: |
              docker stop scientificoperationscenterclient
          
          - name: Generate Doxygen Documentation
            shell: bash
            run: |
              doxygen Doxyfile

          - name: Upload Doxygen Documentation
            uses: actions/upload-artifact@v4
            with:
              name: documentation
              path: ./docs

          - name: Push Docker Images to DockerHub
            if: ${{ github.ref == 'refs/heads/stable' }}
            shell: bash
            run: |
              docker tag scientificoperationscenterapi cherrytreegee811/scientificoperationscenterapi:latest
              docker tag scientificoperationscenterauth cherrytreegee811/scientificoperationscenterauth:latest
              docker tag scientificoperationscenterclient cherrytreegee811/scientificoperationscenterclient:latest
              docker login -u cherrytreegee811 -p ${{ secrets.DOCKER_CRED }}
              docker push cherrytreegee811/scientificoperationscenterapi:latest
              docker push cherrytreegee811/scientificoperationscenterauth:latest
              docker push cherrytreegee811/scientificoperationscenterclient:latest
