name: ScientificOperationsCentre
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
              
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 9.0.x
          
          - name: Install Tools
            shell: bash
            run: |
              sudo apt update -y
              sudo apt install -y nikto doxygen libxml2-utils
          
          - name: Generate SSL cert & key for the SPA client
            shell: bash
            run: |
              openssl req -x509 -newkey rsa:4096 -keyout ScientificOperationsCentre.Client/key.pem -out ScientificOperationsCentre.Client/cert.pem -days 365 -nodes -subj "/CN=localhost"

          - name: Generate SSL cert & key for the SPA client tests
            shell: bash
            run: |
              openssl req -x509 -newkey rsa:4096 -keyout ScientificOperationsCentre.Client.Tests/key.pem -out ScientificOperationsCentre.Client.Tests/cert.pem -days 365 -nodes -subj "/CN=localhost"
              cd ScientificOperationsCentre.Client.Tests
              cat key.pem cert.pem > combined.pem
              rm key.pem cert.pem
            
          - name: Generate SSL cert & key for the REST API
            shell: bash
            run: |
              openssl req -x509 -newkey rsa:4096 -keyout ScientificOperationsCentre.Api/key.pem -out ScientificOperationsCentre.Api/cert.pem -days 365 -nodes -subj "/CN=localhost"

          - name: Build and Run App Containers
            shell: bash
            env:
              JWT_KEY: ${{ secrets.JWT_KEY }}
              APP_ENV: "production"
              GROUND_CONTROL_PASS: ${{ secrets.GROUND_CONTROL_PASS }}
            run: docker compose up -d

          - name: Run API Tests
            shell: bash
            run: |
              mkdir -p APITestResults
              dotnet test ./ScientificOperationsCentre.Api.Tests/ScientificOperationsCentre.Api.Tests.csproj \
                --collect:"XPlat Code Coverage" \
                --results-directory ./APITestResults \
                --os linux \
                --verbosity minimal

          - name: Nikto Scan Backend
            shell: bash
            run: |
              nikto -h https://localhost:8000 -C all

          - name: Stop and Remove API Container
            shell: bash
            run: |
              docker rm -f scientificoperationscentreapi

          - name: Stop and Remove Auth Service Container
            shell: bash
            run: |
              docker rm -f scientificoperationscentreauth
              
          - name: Stop and Remove Database Container
            shell: bash
            run: |
              docker rm -f sqlpreview
              
          - name: Run Client Tests
            shell: bash
            run: |
              mkdir -p ClientTestResults
              dotnet test ./ScientificOperationsCentre.Client.Tests/ScientificOperationsCentre.Client.Tests.csproj --collect:"XPlat Code Coverage" --results-directory ./ClientTestResults --os linux --verbosity minimal

          - name: Nikto Scan Frontend
            shell: bash
            run: |
              nikto -h https://localhost:9000 -C all

          - name: Stop and Remove Client Container
            shell: bash
            run: |
              docker stop scientificoperationscentreclient
          
          - name: Generate Doxygen Documentation
            shell: bash
            run: |
              doxygen Doxyfile

          - name: Upload Doxygen Documentation
            uses: actions/upload-artifact@v4
            with:
              name: documentation
              path: ./docs

          - name: Push Docker Images to DockerHub
            if: ${{ github.ref == 'refs/heads/stable' }}
            shell: bash
            run: |
              docker tag scientificoperationscentreapi cherrytree811/scientificoperationscentreapi:latest
              docker tag scientificoperationscentreauth cherrytree811/scientificoperationscentreauth:latest
              docker tag scientificoperationscentreclient cherrytree811/scientificoperationscentreclient:latest
              docker login -u cherrytree811 -p ${{ secrets.DOCKER_CRED }}
              docker push cherrytree811/scientificoperationscentreapi:latest
              docker push cherrytree811/scientificoperationscentreauth:latest
              docker push cherrytree811/scientificoperationscentreclient:latest
