name: ScientificOperationsCenter
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          
          - name: Install Tools
            shell: bash
            run: |
              dotnet tool install --global dotnet-outdated-tool
              sudo apt install nikto

          - name: Update NuGet Packages
            shell: bash
            run: |
              dotnet outdated -u ./ScientificOperationsCenter.Api/ScientificOperationsCenter.Api.csproj
              dotnet outdated -u ./ScientificOperationsCenter.Client/ScientificOperationsCenter.Client.csproj
      
          - name: Build and Run App Containers
            shell: bash
            run: docker compose up
          
          - name: Run Tests
            shell: bash
            run: |
              dotnet test ./ScientificOperationsCenter.Tests/ScientificOperationsCenter.Tests.csproj --os linux --verbosity minimal
            
          - name: Nikto Scan Frontend
            shell: bash
            run: |
              nikto -h https://localhost:7001 -C all

          - name: Nikto Scan Backend
            shell: bash
            run: |
              nikto -h https://localhost:5001 -C all

          - name: Stop Containers
            shell: bash
            run: |
              docker stop scientificoperationscenterapi
              docker stop scientificoperationscenterclient

          - name: Push to Docker
            if: ${{ github.ref == 'refs/heads/stable' }}
            shell: bash
            run: |
              docker login -u cherrytreegee811 -p ${{ secrets.DOCKER_CRED }}
              docker push cherrytreegee811/scientificoperationscenterapi:latest
              docker push cherrytreegee811/scientificoperationscenterclient:latest
