name: ScientificOperationsCenter
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
              
          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 8.0.x
          
          #- name: Install Tools
            #shell: bash
            #run: |
              #dotnet tool install --global dotnet-outdated-tool
              #sudo apt install nikto

          #- name: Update NuGet Packages
            #shell: bash
            #run: |
              #dotnet outdated -u ./ScientificOperationsCenter.Api/ScientificOperationsCenter.Api.csproj
              #dotnet outdated -u ./ScientificOperationsCenter.Client/ScientificOperationsCenter.Client.csproj
      
          - name: Build and Run App
            shell: bash
            run: |
              dotnet run --project ./ScientificOperationsCenter.Client/ScientificOperationsCenter.Client.csproj --urls=http://localhost:9000 &

          
          #- name: Run API Tests
            #shell: bash
            #run: |
              #dotnet test ./ScientificOperationsCenter.Api.Tests/ScientificOperationsCenter.Api.Tests.csproj --os linux --verbosity minimal 

          #- name: Nikto Scan Backend
           #shell: bash
            #run: |
              #nikto -h http://localhost:8000 -C all

          #- name: Stop and remove API Container
            #shell: bash
            #run: |
              #docker rm -f scientificoperationscenterapi
              
          #- name: Stop and remove database Container
            #shell: bash
            #run: |
             #docker rm -f sqlpreview
              
          - name: Run Client Tests
            shell: bash
            run: |
               dotnet test ./ScientificOperationsCenter.Client.Tests/ScientificOperationsCenter.Client.Tests.csproj --os linux --verbosity minimal

          - name: Nikto Scan Frontend
            shell: bash
            run: |
              nikto -h http://localhost:9000 -C all

          - name: Stop Client Container
            shell: bash
            run: |
              docker stop scientificoperationscenterclient

          - name: Push to Docker
            if: ${{ github.ref == 'refs/heads/stable' }}
            shell: bash
            run: |
              docker tag scientificoperationscenterapi cherrytreegee811/scientificoperationscenterapi:latest
              docker tag scientificoperationscenterclient cherrytreegee811/scientificoperationscenterclient:latest
              docker login -u cherrytreegee811 -p ${{ secrets.DOCKER_CRED }}
              docker push cherrytreegee811/scientificoperationscenterapi:latest
              docker push cherrytreegee811/scientificoperationscenterclient:latest
