name: ScientificOperationsCenter
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          
          - name: Install Tools
            shell: bash
            run: |
              dotnet tool install --global dotnet-outdated-tool
              sudo apt install nikto

          - name: Update NuGet Packages
            shell: bash
            run: |
              dotnet outdated -u ./ScientificOperationsCenter/ScientificOperationsCenter.csproj
         
          - name: Build App Container
            shell: bash
            run: docker build --rm -t cherrytreegee811/scientificoperationscenter ScientificOperationsCenter

          - name: Run App Container
            shell: bash
            run: docker run --rm -dit --name scientificoperationscenter --hostname localhost -p 8080:8080 cherrytreegee811/scientificoperationscenter
          
          - name: Run Tests
            shell: bash
            run: |
              dotnet test ./ScientificOperationsCenter.Tests/ScientificOperationsCenter.Tests.csproj --os linux --verbosity minimal
            
          - name: Nikto Scan
            shell: bash
            run: |
              nikto -h http://localhost:8080 -C all

          - name: Stop Containers
            shell: bash
            run: |
              docker stop scientificoperationscenter
