name: ScientificOperationsCenter
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3

          - name: Build App Container
            shell: bash
            run: docker build --rm -t cherrytreegee811/scientific-ops:latest ./ScientificOperationsCenter
