name: SonarQube Analysis

on:
  push:
    branches:
      - stable
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-project-key: try-free_scientificoperationscenter
          sonar-token: ${{ secrets.SONAR_TOKEN }}
