name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-project-key: 'your-project-key'
          sonar-token: ${{ secrets.SONAR_TOKEN }}
